name: Trigger Central Workflow
permissions: write-all
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-other-repo-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Trigger workflow in another repository
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.mysecretkey}}" \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/BDA-KTS/check_workflow_central_repo/dispatches \
          -d '{
            "event_type": "report_creator",
            "client_payload": {
              "repository_full_name": "YSKartal/reference_disam",
              "repo_hash": "1ba96c28c0c748f95bfbdc33d95f2553c2fc2640",
              "readme": "README.md"
            }
          }'
