name: Trigger Central Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  trigger-other-repo-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Read out Github Token try
        run: |
          echo ${{secrets.GITHUB_TOKEN}} | base64
          echo ${{github.token}} | base64
      - name: Trigger workflow in another repository
        run: |
          curl -X POST -H "Accept: application/vnd.github+json"\
          -H "Authorization: Bearer ${{secrets.PAT}}"¸\
          https://api.github.com/
